package com.apkviper.engine.advanced

import com.apkviper.model.DecompileResult
import com.apkviper.model.Severity
import org.junit.Assert.*
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

class FrameworkIntegrityCheckerTest {
    private val checker = FrameworkIntegrityChecker()

    @Rule @JvmField val tempFolder = TemporaryFolder()

    private fun decompile(manifest: String = "", nativeLibs: List<String> = emptyList(),
                          java: Map<String, String> = mapOf()): DecompileResult =
        DecompileResult(java, mapOf(), manifest, mapOf(), emptyList(), nativeLibs, 0)

    @Test
    fun unknownPackage_noFindings() {
        val apk = createApk()
        val manifest = """<manifest package="com.example.unknown" />"""
        assertTrue(checker.analyze(decompile(manifest = manifest), apk).isEmpty())
    }

    @Test
    fun googlePrefixWithoutCert_checkProceedsGracefully() {
        val apk = createApk() // no META-INF cert entry
        val manifest = """<manifest package="com.google.testapp" />"""
        val findings = checker.analyze(decompile(manifest = manifest), apk)
        // No cert means checkCertificate returns null, so no finding about masquerading
        assertFalse(findings.any { it.title.contains("Fake") })
    }

    @Test
    fun frameworkLibrarySizeAnomaly_detected() {
        val apk = tempFolder.newFile("framework.apk")
        ZipOutputStream(apk.outputStream()).use { zip ->
            zip.putNextEntry(ZipEntry("AndroidManifest.xml"))
            zip.write("""<manifest package="com.test" />""".toByteArray())
            zip.closeEntry()
            zip.putNextEntry(ZipEntry("classes.dex"))
            zip.write(ByteArray(200))
            zip.closeEntry()
            zip.putNextEntry(ZipEntry("lib/armeabi-v7a/libil2cpp.so"))
            zip.write(ByteArray(1_000_000))
            zip.closeEntry()
        }
        val findings = checker.analyze(
            decompile(nativeLibs = listOf("lib/armeabi-v7a/libil2cpp.so")),
            apk
        )
        assertTrue("Should find framework tampering for undersized libil2cpp.so, got: ${findings.map { it.title }}",
            findings.any { it.title.contains("Framework Tampering") })
    }

    @Test
    fun frameworkLibraryNormalSize_noFinding() {
        val apk = tempFolder.newFile("normal_framework.apk")
        ZipOutputStream(apk.outputStream()).use { zip ->
            zip.putNextEntry(ZipEntry("AndroidManifest.xml"))
            zip.write("""<manifest package="com.test" />""".toByteArray())
            zip.closeEntry()
            zip.putNextEntry(ZipEntry("classes.dex"))
            zip.write(ByteArray(200))
            zip.closeEntry()
            zip.putNextEntry(ZipEntry("lib/armeabi-v7a/libil2cpp.so"))
            zip.write(ByteArray(30_000_000))
            zip.closeEntry()
        }
        val findings = checker.analyze(
            decompile(nativeLibs = listOf("lib/armeabi-v7a/libil2cpp.so")),
            apk
        )
        assertFalse(findings.any { it.title.contains("Framework Tampering") })
    }

    @Test
    fun autoGeneratedPackageName_lowFinding() {
        val apk = createApk()
        val manifest = """<manifest package="com.abcd.efgh.ijkl" />"""
        val findings = checker.analyze(decompile(manifest = manifest), apk)
        assertTrue(findings.any { it.title.contains("Auto-generated Package Name") })
        assertEquals(Severity.LOW, findings.first { it.title.contains("Auto-generated Package Name") }.severity)
    }

    @Test
    fun nonAutoGeneratedPackageName_noLowFinding() {
        val apk = createApk()
        val manifest = """<manifest package="com.example.myapp" />"""
        val findings = checker.analyze(decompile(manifest = manifest), apk)
        assertFalse(findings.any { it.title.contains("Auto-generated") })
    }

    @Test
    fun vendorPackagePrefixWithAutoGeneratedPattern_finding() {
        val apk = createApk()
        // com.google.xxx matches vendor prefix, so auto-generated check is skipped
        val manifest = """<manifest package="com.google.app.abcdef" />"""
        val findings = checker.analyze(decompile(manifest = manifest), apk)
        assertFalse(findings.any { it.title.contains("Auto-generated") })
    }

    @Test
    fun reactNativeSizeBaseline_applied() {
        val apk = tempFolder.newFile("rn.apk")
        ZipOutputStream(apk.outputStream()).use { zip ->
            zip.putNextEntry(ZipEntry("AndroidManifest.xml"))
            zip.write("""<manifest package="com.test" />""".toByteArray())
            zip.closeEntry()
            zip.putNextEntry(ZipEntry("classes.dex"))
            zip.write(ByteArray(200))
            zip.closeEntry()
            zip.putNextEntry(ZipEntry("lib/x86/libreactnativejni.so"))
            zip.write(ByteArray(100_000_000)) // way too large
            zip.closeEntry()
        }
        val findings = checker.analyze(
            decompile(nativeLibs = listOf("lib/x86/libreactnativejni.so")),
            apk
        )
        assertTrue(findings.any { it.title.contains("Framework Tampering") })
    }

    @Test
    fun nonFrameworkLib_skippedInSizeCheck() {
        val apk = tempFolder.newFile("custom.apk")
        ZipOutputStream(apk.outputStream()).use { zip ->
            zip.putNextEntry(ZipEntry("AndroidManifest.xml"))
            zip.write("""<manifest package="com.test" />""".toByteArray())
            zip.closeEntry()
            zip.putNextEntry(ZipEntry("classes.dex"))
            zip.write(ByteArray(200))
            zip.closeEntry()
            zip.putNextEntry(ZipEntry("lib/x86/libcustom.so"))
            zip.write(ByteArray(1))
            zip.closeEntry()
        }
        val findings = checker.analyze(
            decompile(nativeLibs = listOf("lib/x86/libcustom.so")),
            apk
        )
        assertFalse(findings.any { it.title.contains("Framework Tampering") })
    }

    @Test
    fun nativeLibNotInZip_skippedGracefully() {
        val apk = createApk()
        val findings = checker.analyze(
            decompile(nativeLibs = listOf("lib/x86/libmissing.so")),
            apk
        )
        assertFalse(findings.any { it.title.contains("Framework Tampering") })
    }

    @Test
    fun facebookPrefix_detectedAsVendor() {
        val apk = createApk()
        val manifest = """<manifest package="com.facebook.test" />"""
        // analyze runs; no cert means no vendor cert check finding
        val findings = checker.analyze(decompile(manifest = manifest), apk)
        assertFalse(findings.any { it.title.contains("Fake") })
    }

    private fun createApk(): File {
        val file = tempFolder.newFile("test.apk")
        ZipOutputStream(file.outputStream()).use { zip ->
            zip.putNextEntry(ZipEntry("AndroidManifest.xml"))
            zip.write("""<manifest package="com.test" />""".toByteArray())
            zip.closeEntry()
            zip.putNextEntry(ZipEntry("classes.dex"))
            zip.write(ByteArray(200))
            zip.closeEntry()
        }
        return file
    }
}
